#!/bin/bash
#
# Slurm submission script for AlphaFold 2 pipeline.
#

#SBATCH --job-name=AF2                  # Name of the job
#SBATCH --nodes=1                       # Use a single node
#SBATCH --time=01:00:00                 # Maximum execution time: 1 hour
#SBATCH --partition gpu_a100            # Use A100 partition for AF2. Switch to rome or genoa when not using GPU
#SBATCH --gpus 1                        # Use a single GPU. Remove if not using GPU
#SBATCH --output=AF2%j.out              # Standard output log
#SBATCH --error=AF2%j.err               # Standard error log

# Path to the dataset.
DATA_PATH=/projects/2/managed_datasets/AlphaFold/2.3.1

# --- VARIABLE DEFINITIONS ---
# Define the base project directory
PROJECT_SPACE=/projects/2/prjs0823/ProteinFolding-Design/apptainers # Change this to your project directory

# File path of the input .fasta file. Change you to your desired file
INPUT_FASTA=${PROJECT_SPACE}/alphafold2/inputs/rcsb_pdb_7XTB.fasta

# Location where output files are written to.
OUTPUT_PATH=${PROJECT_SPACE}/alphafold2/outputs/

SIF_FILE=${DATA_PATH}/alphafold_2_latest.sif

bind_args="-B /projects/2/managed_datasets/AlphaFold/2.3.1:/data -B ${PROJECT_SPACE} --pwd /app/alphafold"

data_args="--data_dir /data --bfd_database_path /data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt --mgnify_database_path /data/mgnify/mgy_clusters_2022_05.fa --template_mmcif_dir /data/pdb_mmcif/mmcif_files --obsolete_pdbs_path /data/pdb_seqres/pdb_seqres.txt --uniref90_database_path /data/uniref90/uniref90.fasta --uniref30_database_path /data/uniref30/UniRef30_2021_03 --pdb70_database_path /data/pdb70/pdb70"

# Environment variables for running AlphaFold 2 with GPU support and memory management. Remove the --nv flag if you want to run on CPU only 
env_args="--env TF_FORCE_UNIFIED_MEMORY=1,XLA_PYTHON_CLIENT_MEM_FRACTION=4.0,OPENMM_CPU_THREADS=8 --nv"

# arguments
cmd_args="--fasta_paths ${INPUT_FASTA}
--output_dir ${OUTPUT_PATH}
--db_preset full_dbs
--max_template_date 2023-03-20
--use_gpu_relax
${data_args}"

unset LD_PRELOAD
echo "Running AlphaFold 2 with the following command arguments:"
echo "${cmd_args}"

echo "Full command: PYTHONNOUSERSITE=1 apptainer run --no-home ${env_args} ${bind_args} ${SIF_FILE} ${cmd_args}"
PYTHONNOUSERSITE=1 apptainer run --no-home ${env_args} ${bind_args} ${SIF_FILE} ${cmd_args}
